// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// PHS: porting from C++ done (not tested)

package org.usfirst.frc4513.Showbot.subsystems;

import org.usfirst.frc4513.Showbot.RobotMap;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.Relay;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Cannon extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Relay cannonSpike = RobotMap.cannonCannonSpike;
    private final DoubleSolenoid dblSolenoid = RobotMap.cannonDblSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    // PHS: manually added methods for controlling this subsystem
    // PHSQUESTION: is there a way to get these methods specified in Robotbuilder?
    // PHSNOTE: In Java, Relay constants must be obtained from Relay base class, not derived class
    //          ditto for Solenoids, etc.
    public void cannonFireOn(){
    	cannonSpike.set(Relay.Value.kForward);
    }
    public void cannonFireOff(){
    	cannonSpike.set(Relay.Value.kOff);
    }
    public void cannonRaise(){
    	dblSolenoid.set(DoubleSolenoid.Value.kReverse);
    }
    public void cannonLower(){
    	dblSolenoid.set(DoubleSolenoid.Value.kForward);
    }
    public void cannonStop(){
    	dblSolenoid.set(DoubleSolenoid.Value.kOff);
    }
    
}

