// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// PHS: C++ port done (not yet tested)

package org.usfirst.frc4513.Showbot.subsystems;

import org.usfirst.frc4513.Showbot.RobotMap;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Leds extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController ledsBlurCtrlr = RobotMap.ledsledsBlurCtrlr;
    private final SpeedController ledsRedCtrlr = RobotMap.ledsledsRedCtrlr;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    // PHS: ported these from C++
    // PHSNOTE: Looks like ledsBlurCtrlr was intended to be named ledsBlueCtrlr.
    //          If we go back and rename it in Robotbuilder, will it patch this code?
    //          Doubtful, as this is not generated code.
    public void ledsOn() {
    	ledsBlurCtrlr.set(1.0);
    	ledsRedCtrlr.set(1.0);
    }

    public void ledsOff() {
    	ledsBlurCtrlr.set(0.0);
    	ledsRedCtrlr.set(0.0);
    }

    public void ledsLight(float RedVal, float BlueVal){
    	ledsBlurCtrlr.set(BlueVal);
    	ledsRedCtrlr.set(RedVal);
    }    
}

